#!/bin/bash
echo
# Check for root user
if [[ $EUID -ne 0 ]]; then
    echo "You must be a root user to run this." 2>&1
    exit 1
fi
# Check for efi boot
echo "ls /sys/firmware/efi/efivars"
ls /sys/firmware/efi/efivars
echo
echo "Press 'Ctrl+c' to exit OR 'Enter' to continue"
read
# Update system clock
timedatectl set-ntp true
# List partitions
fdisk -l
echo
lsblk
echo
# Edit partitions
echo "cfdisk"
read
cfdisk
# List partitions
fdisk -l
echo
lsblk
# Edit partitions
echo "cfdisk"
read
cfdisk
# List partitions
fdisk -l
echo
lsblk
echo
# Input locations of efi partition and root partition
read -p "efipartition (/dev/sdax) = " efipartition
echo $efipartition
echo
read -p "ospartition (/dev/sdax) = " ospartition
echo $ospartition
echo
# Format efi partition as fat32
echo mkfs.fat -F32 $efipartition
mkfs.fat -F32 $efipartition
echo
# Format root partition as ext4
echo mkfs.ext4 $ospartition
mkfs.ext4 $ospartition
echo
# Mount root partition to /mnt
mount $ospartition /mnt
# Install the base and base-devel package groups using pacstrap
echo "pacstrap /mnt base base-devel"
pacstrap /mnt base base-devel
echo
# Generate fstab
echo "Generate fstab."
genfstab -U /mnt >> /mnt/etc/fstab
echo
cat /mnt/etc/fstab
# Copy remaining installation files to /mnt, make them executable,
# and remove the cloned install folder
cp /root/install/chroot /mnt
cp /root/install/gnome1 /mnt
cp /root/install/gnome2 /mnt
cp /root/install/deepin1 /mnt
chmod +x /mnt/chroot
chmod +x /mnt/gnome1
chmod +x /mnt/gnome2
chmod +x /mnt/deepin1
rm -r /root/install
#
#--------------------------------------------------------------------
#mkdir /mnt/hostlvm
#mount --bind /run/lvm /mnt/hostlvm
#--------------------------------------------------------------------
# echo "arch-chroot /mnt"
# arch-chroot /mnt
#--------------------------------------------------------------------
# Run the chroot script in the new system through chroot 
arch-chroot /mnt ./chroot
# Run below commands in the new system through chroot to exit
# -
#arch-chroot /mnt /bin/bash <<EOF
#exit
#EOF
# -
# Unmount and reboot
umount -a
reboot
#--------------------------------------------------------------------
