#!/bin/bash
# Check if user is root
if [[ $EUID -ne 0 ]]; then
    echo "You must be a root user to run this." 2>&1
    exit 1
fi
# Check if system is booted in efi mode
ls /sys/firmware/efi/efivars
echo
echo "Press 'Ctrl+c' to exit OR 'Enter' to continue"
read
# Update system clock
timedatectl set-ntp true
# List partitions
fdisk -l
echo
lsblk
echo
# Edit partitions
echo "cfdisk"
read
cfdisk
# List partitions
fdisk -l
echo
lsblk
echo
# Input locations of efi partition and root partition
read -p "efipartition (/dev/sdax) = " efipartition
sudo sed -i "s@EFIPARTITION@$efipartition@g" /root/install/chroot
echo
read -p "ospartition (/dev/sdax) = " ospartition
echo
# Input bootloader id
read -p "Enter your preferred bootloader-id: " bootloaderid
sudo sed -i "s@BOOTLOADERID@$bootloaderid@g" /root/install/chroot
echo
# Input hostname
read -p "Enter your hostname: " hostname
sudo sed -i "s@HOSTNAME@$hostname@g" /root/install/chroot
echo
# Input username
read -p "Enter your preferred username: " username
sudo sed -i "s@USERNAME@$username@g" /root/install/chroot
echo
# Format efi partition as fat32
mkfs.fat -F32 $efipartition
echo
# Format root partition as ext4
mkfs.ext4 $ospartition
echo
# Mount root partition to /mnt
mount $ospartition /mnt
# Install the base and base-devel package groups using pacstrap
pacstrap /mnt base base-devel
echo
# Generate fstab
genfstab -U /mnt >> /mnt/etc/fstab
echo
cat /mnt/etc/fstab
# Copy remaining installation files to /mnt, make them executable,
cp /root/install/*ARCHBYTE /mnt
chmod +x /mnt/*ARCHBYTE
# Remove the cloned install folder
rm -r /root/install
#--------------------------------------------------------------------
# Run the chroot script in the new system through chroot 
arch-chroot /mnt ./chrootARCHBYTE
# Unmount and reboot
umount -a
reboot
