#!/bin/bash
# Check for root user
if [[ $EUID -ne 0 ]]; then
    echo "You must be a root user to run this." 2>&1
    exit 1
fi
#--------------------------------------------------------------------
# Set the timezone to US-Pacific
ln -sf /usr/share/zoneinfo/US/Pacific /etc/localtime
# Generate /etc/adjtime
hwclock --systohc --utc
# Uncomment locale
echo "nano /etc/locale.gen - Setting locale: en_US.UTF-8 UTF-8 for American-English."
sed -i '/#en_US.UTF-8 UTF-8/s/^#//g' /etc/locale.gen
echo
# Set the LANG variable
echo "LANG=en_US.UTF-8"  > /etc/locale.conf
# Generate locale
locale-gen
echo
# Set hostname
echo HOSTNAME > /etc/hostname
# Input root password
echo "Enter root password."
passwd
echo
# Create /boot/efi directory
mkdir /boot/efi
# Mount efi partition to the /boot/efi directory
mount EFIPARTITION /boot/efi
echo
# Install some required packages for booting and stuff
pacman -S --needed --noconfirm intel-ucode grub efibootmgr sudo networkmanager os-prober wget
echo
# Install grub to /boot/efi
grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=BOOTLOADERID
echo
# Change grub timeout to 0
sudo sed -i '4s/5/0/' /etc/default/grub
# Generate grub config file
sudo grub-mkconfig -o /boot/grub/grub.cfg
echo
# Enable network manager
systemctl enable NetworkManager
# Create user
useradd -m -g users -G wheel -s /bin/bash USERNAME
echo
# Input user password
echo Enter your user password.
passwd USERNAME
echo
# Set admin priviliges
echo "Uncommenting the wheel group line."
sudo sed -i '/# %wheel ALL=(ALL) ALL/s/^#//g' /etc/sudoers
#--------------------------------------------------------------------
# Move remaining setup files to user home directory
rm /chrootARCHBYTE
mv /*ARCHBYTE /home/USERNAME
# Exit from chroot (or chroot script?)
exit
