#!/bin/bash
echo
echo "Press 'Ctrl+c' to exit OR 'Enter' to continue"
read
#------------------------------------------------------------------------------------------------------------------------------------------
nmcli device wifi list
echo
read -p "Enter your wifi SSID: " ssid
read -p "Enter your wifi password: " wifipass
nmcli device wifi connect $ssid password $wifipass
echo
#------------------------------------------------------------------------------------------------------------------------------------------
sudo pacman -Syu
#------------------------------------------------------------------------------------------------------------------------------------------
sudo pacman -S --needed util-linux base-devel git wget bash curl dbus perl less xorg-server xorg-xinit xorg-xprop gnome-shell nautilus gnome-system-monitor chrome-gnome-shell gnome-tweak-tool gnome-screenshot gnome-control-center gnome-terminal gnome-backgrounds gnome-power-manager chromium eog xdg-user-dirs xdotool wmctrl plank synergy qt5-base tree neofetch gdm reflector gparted
#
sudo systemctl enable fstrim.timer
#------------------------------------------------------------------------------------------------------------------------------------------
git clone https://aur.archlinux.org/pikaur.git
cd pikaur
makepkg -fsri
cd /home/$USER
pikaur -S ttf-clear-sans pamac-aur nautilus-admin sublime-text-dev libinput-gestures automathemely la-capitaine-icon-theme capitaine-cursors
echo
#------------------------------------------------------------------------------------------------------------------------------------------
cd /home/$USER
wget -O gnome-shell-extension-installer "https://github.com/brunelli/gnome-shell-extension-installer/raw/master/gnome-shell-extension-installer"
chmod +x gnome-shell-extension-installer
sudo mv gnome-shell-extension-installer /usr/bin/
#
gnome-shell-extension-installer 19 545 277 36 1303 118 1297 800 826
#------------------------------------------------------------------------------------------------------------------------------------------
echo "Enabling gdm service..."
sudo systemctl enable gdm
echo
#
sudo sed -i '/WaylandEnable=false/s/^#//' /etc/gdm/custom.conf
echo '# Enable automatic login for user' | sudo tee --append /etc/gdm/custom.conf
echo '[daemon]' | sudo tee --append /etc/gdm/custom.conf
echo 'AutomaticLogin=navtoj' | sudo tee --append /etc/gdm/custom.conf
echo 'AutomaticLoginEnable=True' | sudo tee --append /etc/gdm/custom.conf
echo
#
echo Replace "navtoj" with your username in the following file. 
echo
echo Press ENTER to continue.
read
sudo nano /etc/gdm/custom.conf
#------------------------------------------------------------------------------------------------------------------------------------------
echo "Editing /etc/hosts file for sublime text..."
echo '127.0.0.1       www.sublimetext.com' | sudo tee --append /etc/hosts
echo '127.0.0.1       license.sublimehq.com'| sudo tee --append /etc/hosts
#------------------------------------------------------------------------------------------------------------------------------------------
cp /etc/libinput-gestures.conf ~/.config/libinput-gestures.conf
sed -i '50s/.*/gesture swipe up 4 _internal ws_up/' ~/.config/libinput-gestures.conf
sed -i '63s/.*/gesture swipe down 4 _internal ws_down/' ~/.config/libinput-gestures.conf
sed -i '67s/.*/gesture swipe left 4 xdotool key alt+Right/' ~/.config/libinput-gestures.conf
sed -i '70s/.*/gesture swipe right 4 xdotool key alt+Left/' ~/.config/libinput-gestures.conf
sed -i '118s/.*/gesture swipe left_up 4 xdotool key super+a/' ~/.config/libinput-gestures.conf
sed -i '119s/.*/gesture swipe left_down 4 xdotool key super+s/' ~/.config/libinput-gestures.conf
#------------------------------------------------------------------------------------------------------------------------------------------
echo "export PATH=doublequotes/root/.gem/ruby/2.5.0/bin:dollarsignPATHdoublequotes" >> ~/.bashrc
sudo sed -i '10s/doublequotes/"/' ~/.bashrc
sudo sed -i '10s/doublequotes/"/' ~/.bashrc
sudo sed -i '10s/dollarsign/$/' ~/.bashrc
#------------------------------------------------------------------------------------------------------------------------------------------
subl3
#
sudo gpasswd -a $USER input
mkdir /home/$USER/.config/autostart
cp /usr/share/applications/libinput-gestures.desktop /home/$USER/.config/autostart
cp /usr/share/applications/plank.desktop /home/$USER/.config/autostart
cp /usr/share/applications/synergy.desktop /home/$USER/.config/autostart
#cp /usr/share/applications/automathemely.desktop /home/$USER/.config/autostart
#------------------------------------------------------------------------------------------------------------------------------------------
sudo cp /usr/share/plank/themes/Default/dock.theme /usr/share/plank/themes/Default/dockbackup.theme && sudo cp /usr/share/plank/themes/Transparent/dock.theme /usr/share/plank/themes/Default/dock.theme
#
sudo rm -r /usr/share/backgrounds/gnome
sudo rm -r /usr/share/gnome-background-properties
#
sudo git clone https://github.com/archbyte/mojave /usr/share/backgrounds/gnome
sudo rm -r /usr/share/backgrounds/gnome/.git
#
sudo mkdir /usr/share/gnome-background-properties
sudo mv /usr/share/backgrounds/gnome/gnome-backgrounds.xml /usr/share/gnome-background-properties
#------------------------------------------------------------------------------------------------------------------------------------------
sudo git clone https://github.com/EliverLara/Ant-Nebula --branch slim /usr/share/themes/Ant-Nebula
sudo git clone https://github.com/EliverLara/Ant-Dracula --branch slim /usr/share/themes/Ant-Dracula
#------------------------------------------------------------------------------------------------------------------------------------------
sudo ln -sf /dev/null /etc/systemd/system/avahi-daemon.service
sudo ln -sf /dev/null /etc/systemd/system/avahi-daemon.socket
sudo ln -sf /dev/null /etc/systemd/system/dbus-org.freedesktop.Avahi.service
sudo bash -c "echo 'NoDisplay=true' >> /usr/share/applications/avahi-discover.desktop"
sudo bash -c "echo 'NoDisplay=true' >> /usr/share/applications/bssh.desktop"
sudo bash -c "echo 'NoDisplay=true' >> /usr/share/applications/bvnc.desktop"
sudo update-desktop-database
#------------------------------------------------------------------------------------------------------------------------------------------
timedatectl set-ntp 1
#
cat << EOT >> /home/$USER/.config/sublime-text-3/Local/License.sublime_license
----- BEGIN LICENSE -----
sgbteam
Single User License
EA7E-1153259
8891CBB9 F1513E4F 1A3405C1 A865D53F
115F202E 7B91AB2D 0D2A40ED 352B269B
76E84F0B CD69BFC7 59F2DFEF E267328F
215652A3 E88F9D8F 4C38E3BA 5B2DAAE4
969624E7 DC9CD4D5 717FB40C 1B9738CF
20B3C4F1 E917B5B3 87C38D9C ACCE7DD8
5F7EF854 86B9743C FADC04AA FB0DA5C0
F913BE58 42FEA319 F954EFDD AE881E0B
------ END LICENSE ------
EOT
#------------------------------------------------------------------------------------------------------------------------------------------
cd /home/$USER
sudo rm -r pikaur
sudo rm /chroot
echo "Rebooting..."
sudo reboot
