#!/bin/bash
echo
echo "Press 'Ctrl+c' to exit OR 'Enter' to continue"
read
#------------------------------------------------------------------------------------------------------------------------------------------
nmcli device wifi list
echo
read -p "Enter your wifi SSID: " ssid
read -p "Enter your wifi password: " wifipass
nmcli device wifi connect $ssid password $wifipass
echo
#------------------------------------------------------------------------------------------------------------------------------------------
sudo pacman -Syu
#------------------------------------------------------------------------------------------------------------------------------------------
git clone https://aur.archlinux.org/pikaur.git
cd pikaur
makepkg -fsri
cd /home/$USER
echo "To install AUR packages, use the following command: pikaur -S package_name"
#
timedatectl set-ntp 1
#
cd /home/$USER
sudo rm -r pikaur
sudo rm /chroot
echo "Press 'Enter' to Reboot"
read
sudo reboot
