#!/bin/bash
# Connect to wifi
nmcli device wifi list
echo
read -p "Enter your wifi SSID: " ssid
read -p "Enter your wifi password: " wifipass
nmcli device wifi connect $ssid password $wifipass
echo
# Update system
sudo pacman -Syu
# Install packages for deepin desktop environment and other cool stuff
sudo pacman -S --needed base-devel git wget ntfs-3g xorg-server xorg-server xorg-xinit xorg-xprop xdg-user-dirs xdotool wmctrl tree neofetch reflector adobe-source-code-pro-fonts plasma-desktop konsole dolphin ark gwenview kate lightdm lightdm-gtk-greeter
# plank synergy bluez-utils
# deepin-session-ui ### TOO MUCH EXTRA STUFF NEEDED TO INSTALL
#
# Install pikaur: an aur helper
git clone https://aur.archlinux.org/pikaur.git
cd pikaur
makepkg -fsri
cd /home/$USER
pikaur -S pamac-aur 
# sublime-text-dev chromium-widevine ttf-clear-sans libinput-gestures la-capitaine-icon-theme capitaine-cursors
echo
# Customize display manager
# -> Check for available greeters
ls -1 /usr/share/xgreeters/
sudo nano /etc/lightdm/lightdm.conf # greeter-session=lightdm-gtk-greeter
# Enable display manager
echo "Enabling display manager service..."
sudo systemctl enable lightdm
echo
# Enable the bluetooth service
#echo "Enabling bluetooth service..."
#sudo systemctl enable bluetooth
#echo
#
# Edit hosts file for sublime text
#echo "Editing /etc/hosts file for sublime text..."
#echo '127.0.0.1       www.sublimetext.com' | sudo tee --append /etc/hosts
#echo '127.0.0.1       license.sublimehq.com'| sudo tee --append /etc/hosts
# Set custom touchpad gestures
cp /etc/libinput-gestures.conf ~/.config/libinput-gestures.conf
#sed -i '50s/.*/gesture swipe up 3 _internal ws_up/' ~/.config/libinput-gestures.conf
#sed -i '63s/.*/gesture swipe down 3 _internal ws_down/' ~/.config/libinput-gestures.conf
#sed -i '67s/.*/gesture swipe left 3 xdotool key alt+Right/' ~/.config/libinput-gestures.conf
#sed -i '70s/.*/gesture swipe right 3 xdotool key alt+Left/' ~/.config/libinput-gestures.conf
#sed -i '118s/.*/gesture swipe left_up 3 xdotool key super+a/' ~/.config/libinput-gestures.conf
#sed -i '119s/.*/gesture swipe left_down 3 xdotool key super+s/' ~/.config/libinput-gestures.conf
#sed -i '132s/.*/gesture pinch clockwise xdotool key super+Right/' ~/.config/libinput-gestures.conf
#sed -i '133s/.*/gesture pinch anticlockwise xdotool key super+Left/' ~/.config/libinput-gestures.conf
# Run sublime-text to generate some config data
#subl3
# Set apps to autostart
sudo gpasswd -a $USER input
libinput-gestures-setup autostart
#mkdir /home/$USER/.config/autostart
#cp /usr/share/applications/libinput-gestures.desktop /home/$USER/.config/autostart
#cp /usr/share/applications/plank.desktop /home/$USER/.config/autostart
#cp /usr/share/applications/synergy.desktop /home/$USER/.config/autostart
# Set plank theme
sudo cp /usr/share/plank/themes/Default/dock.theme /usr/share/plank/themes/Default/dockbackup.theme && sudo cp /usr/share/plank/themes/Transparent/dock.theme /usr/share/plank/themes/Default/dock.theme
# Set desktop and lock screen wallpaper to mojave
#sudo rm -r /usr/share/backgrounds/gnome
#sudo rm -r /usr/share/gnome-background-properties
# ^
#sudo git clone https://github.com/archbyte/mojave /usr/share/backgrounds/gnome
#sudo rm -r /usr/share/backgrounds/gnome/.git
# ^
#sudo mkdir /usr/share/gnome-background-properties
#sudo mv /usr/share/backgrounds/gnome/gnome-backgrounds.xml /usr/share/gnome-background-properties
# Install some shell themes
#sudo git clone https://github.com/EliverLara/Ant-Nebula --branch slim /usr/share/themes/Ant-Nebula
#sudo git clone https://github.com/paullinuxthemer/Dark-Side /usr/share/themes/Dark-Side
# Keep the avahi apps from showing up in the apps view
#sudo ln -sf /dev/null /etc/systemd/system/avahi-daemon.service
#sudo ln -sf /dev/null /etc/systemd/system/avahi-daemon.socket
#sudo ln -sf /dev/null /etc/systemd/system/dbus-org.freedesktop.Avahi.service
#sudo bash -c "echo 'NoDisplay=true' >> /usr/share/applications/avahi-discover.desktop"
#sudo bash -c "echo 'NoDisplay=true' >> /usr/share/applications/bssh.desktop"
#sudo bash -c "echo 'NoDisplay=true' >> /usr/share/applications/bvnc.desktop"
#sudo update-desktop-database
# Do something related to time?
sudo timedatectl set-ntp 1
# Enter sublime license ### NO LONGER WORKING SINCE VERSION 3200 ###
#cat << EOT >> /home/$USER/.config/sublime-text-3/Local/License.sublime_license
#----- BEGIN LICENSE -----
#sgbteam
#Single User License
#EA7E-1153259
#8891CBB9 F1513E4F 1A3405C1 A865D53F
#115F202E 7B91AB2D 0D2A40ED 352B269B
#76E84F0B CD69BFC7 59F2DFEF E267328F
#215652A3 E88F9D8F 4C38E3BA 5B2DAAE4
#969624E7 DC9CD4D5 717FB40C 1B9738CF
#20B3C4F1 E917B5B3 87C38D9C ACCE7DD8
#5F7EF854 86B9743C FADC04AA FB0DA5C0
#F913BE58 42FEA319 F954EFDD AE881E0B
#------ END LICENSE ------
#EOT
# Script to make the post script run after reboot
cat << EOT >> /home/$USER/.config/autostart/kdepostinstallscript.desktop
[Desktop Entry]
Type=Application
Version=1.0
Name=postinstallscript
Exec=/home/$USER/kde2
Terminal=true
EOT
chmod +x /home/$USER/.config/autostart/gnomepostinstallscript.desktop
#
# Remove the pikaur folder and the chroot file
cd /home/$USER
sudo rm -r pikaur
sudo rm /chroot
# Reboot
sudo reboot
