#!/bin/bash
echo
echo "Press 'Ctrl+c' to exit OR 'Enter' to continue"
read
#------------------------------------------------------------------------------------------------------------------------------------------
automathemely
#------------------------------------------------------------------------------------------------------------------------------------------
#sudo rm -r /usr/share/backgrounds/gnome
#sudo rm -r /usr/share/gnome-background-properties
#
#sudo git clone https://github.com/archbyte/mojave /usr/share/backgrounds/gnome
#sudo rm -r /usr/share/backgrounds/gnome/.git
#
#sudo mkdir /usr/share/gnome-background-properties
#sudo mv /usr/share/backgrounds/gnome/gnome-backgrounds.xml /usr/share/gnome-background-properties
#
#gsettings set org.gnome.desktop.background picture-uri /usr/share/backgrounds/gnome/mojave-timed.xml
#gsettings set org.gnome.desktop.screensaver picture-uri /usr/share/backgrounds/gnome/mojave-timed.xml
#------------------------------------------------------------------------------------------------------------------------------------------
#sudo git clone https://github.com/EliverLara/Ant-Nebula --branch slim /usr/share/themes/Ant-Nebula
#sudo git clone https://github.com/EliverLara/Ant-Dracula --branch slim /usr/share/themes/Ant-Dracula
#gsettings set org.gnome.desktop.interface gtk-theme "Ant-Nebula"
#gsettings set org.gnome.desktop.wm.preferences theme "Ant-Nebula"
#gsettings set org.gnome.desktop.interface icon-theme 'la-capitaine'
#gsettings set org.gnome.desktop.interface cursor-theme 'capitaine-cursors'
#
#automathemely --setting themes.light=Ant-Nebula
#automathemely --setting themes.dark=Ant-Dracula
#automathemely --setting offset.sunrise=0
#automathemely --setting offset.sunset=0
#automathemely --setting location.auto_enabled=true
#automathemely --setting misc.notifications=false
#automathemely --setting extras.atom.enabled=false
#automathemely --setting extras.vscode.enabled=false
#automathemely --update
#automathemely --restart
#cp /usr/share/applications/automathemely.desktop /home/$USER/.config/autostart
#
#gsettings set org.gnome.desktop.wm.preferences button-layout 'close,minimize,maximize:'
#------------------------------------------------------------------------------------------------------------------------------------------
#sudo pacman -S --needed ruby ruby-docs rubygems
#sudo gem install rdoc
#sudo gem install sass
#cd /usr/share/themes/Ant-Dracula/gtk-3.20/
#sudo sed -i '22s/ff79c6/00b0ff/' _colors.scss
#sudo sass gtk.scss gtk.css
#------------------------------------------------------------------------------------------------------------------------------------------
#sudo git clone https://github.com/rockon999/dynamic-panel-transparency.git
#sudo mv dynamic-panel-transparency/dynamic-panel-transparency@rockon999.github.io ~/.local/share/gnome-shell/extensions/
#sudo rm -r dynamic-panel-transparency
#------------------------------------------------------------------------------------------------------------------------------------------
#sudo pacman -S fprintd
#sudo sed -i.bkp '/#%PAM-1.0/a auth       sufficient   pam_fprintd.so' /etc/pam.d/polkit-1
#fprintd-enroll
#sudo sed -i.bkp '/auth		sufficient	pam_rootok.so/a auth            sufficient      pam_fprintd.so' /etc/pam.d/su
#sudo sed -i.bkp '/#%PAM-1.0/a auth            sufficient      pam_fprintd.so' /etc/pam.d/sudo
#sudo cat << EOT >> /etc/polkit-1/rules.d/50-net.reactivated.fprint.device.enroll.rules
#polkit.addRule(function (action, subject) {
#  if (action.id == "net.reactivated.fprint.device.enroll") {
#    return subject.user == "root" ? polkit.Result.YES : polkit.result.NO
#  }
#})
#EOT
#------------------------------------------------------------------------------------------------------------------------------------------
sudo pacman -S --needed ruby ruby-docs rubygems
sudo gem install rdoc
sudo gem install sass
cd /usr/share/themes/Ant-Dracula/gtk-3.20/
sudo sed -i '22s/ff79c6/00b0ff/' _colors.scss
sudo sass gtk.scss gtk.css
#
#sudo -u gdm dbus-launch gsettings set org.gnome.desktop.peripherals.touchpad tap-to-click true
gsettings set org.gnome.desktop.peripherals.touchpad tap-to-click true
gsettings set org.gnome.Terminal.Legacy.Settings default-show-menubar false
gsettings set org.gnome.Terminal.Legacy.Keybindings toggle-menubar '<Alt>m'
gsettings set org.gnome.settings-daemon.plugins.xsettings antialiasing 'rgba'
gsettings set org.gnome.settings-daemon.plugins.color night-light-enabled true
gsettings set org.gnome.mutter attach-modal-dialogs false
gsettings set org.gnome.mutter center-new-windows true
gsettings set org.gnome.mutter edge-tiling true
gsettings set org.gnome.desktop.wm.preferences resize-with-right-button false
gsettings set org.gnome.nautilus.window-state sidebar-width 157
gsettings set org.gnome.nautilus.window-state initial-size '(794, 485)'
gsettings set org.gnome.desktop.interface show-battery-percentage true
gsettings set org.gnome.desktop.interface clock-show-date true
gsettings set org.gnome.desktop.interface clock-show-seconds true
gsettings set org.gnome.desktop.datetime automatic-timezone true
gsettings set org.gnome.desktop.interface clock-format 12h
gsettings set org.gnome.desktop.interface font-name 'Clear Sans Medium, Medium 11'
gsettings set org.gnome.desktop.interface document-font-name 'Clear Sans 11'
gsettings set org.gnome.desktop.interface monospace-font-name 'Clear Sans Thin, weight=255 11'
gsettings set org.gnome.desktop.wm.preferences titlebar-font 'Clear Sans Bold 11'
gsettings set org.gnome.desktop.wm.preferences button-layout 'close,minimize,maximize:'
gsettings set org.gnome.desktop.interface icon-theme 'la-capitaine'
gsettings set org.gnome.desktop.interface cursor-theme 'capitaine-cursors'
gsettings set org.gnome.desktop.background picture-uri /usr/share/backgrounds/gnome/mojave-timed.xml
gsettings set org.gnome.desktop.screensaver picture-uri /usr/share/backgrounds/gnome/mojave-timed.xml
#
automathemely --setting desktop_environment=gnome
automathemely --setting themes.gnome.light.gtk=Ant-Nebula
automathemely --setting themes.gnome.light.icons=la-capitaine
automathemely --setting themes.gnome.light.shell=Ant-Nebula
automathemely --setting themes.gnome.dark.gtk=Ant-Dracula
automathemely --setting themes.gnome.dark.icons=la-capitaine
automathemely --setting themes.gnome.dark.shell=Ant-Nebula
automathemely --setting location.auto_enabled=True
#automathemely --setting misc.notifications=False
automathemely --update
automathemely --restart
#------------------------------------------------------------------------------------------------------------------------------------------
sudo rm /home/$USER/de
sudo reboot
