#!/bin/bash
#------------------------------------------------------------------------------------------------------------------------------------------
automathemely
#------------------------------------------------------------------------------------------------------------------------------------------
#sudo pacman -S --needed util-linux
#sudo systemctl enable fstrim.timer
#------------------------------------------------------------------------------------------------------------------------------------------
#gsettings set org.gnome.Terminal.Legacy.Keybindings toggle-menubar '<Alt>m'
gsettings set org.gnome.Terminal.Legacy.Settings default-show-menubar false
gsettings set org.gnome.settings-daemon.plugins.xsettings antialiasing 'rgba'
gsettings set org.gnome.settings-daemon.plugins.color night-light-enabled true
gsettings set org.gnome.mutter attach-modal-dialogs false
gsettings set org.gnome.mutter center-new-windows true
gsettings set org.gnome.mutter edge-tiling true
gsettings set org.gnome.desktop.wm.preferences resize-with-right-button false
gsettings set org.gnome.nautilus.window-state sidebar-width 157
gsettings set org.gnome.nautilus.window-state initial-size '(794, 485)'
gsettings set org.gnome.desktop.interface show-battery-percentage true
gsettings set org.gnome.desktop.interface clock-show-date true
gsettings set org.gnome.desktop.interface clock-show-seconds true
gsettings set org.gnome.desktop.datetime automatic-timezone true
gsettings set org.gnome.desktop.interface clock-format 12h
gsettings set org.gnome.desktop.interface font-name 'Clear Sans Medium, Medium 11'
gsettings set org.gnome.desktop.interface document-font-name 'Clear Sans 11'
gsettings set org.gnome.desktop.interface monospace-font-name 'Clear Sans Thin, weight=255 11'
gsettings set org.gnome.desktop.wm.preferences titlebar-font 'Clear Sans Bold 11'
gsettings set org.gnome.desktop.wm.preferences button-layout 'close,minimize,maximize:'
gsettings set org.gnome.desktop.interface icon-theme 'la-capitaine'
gsettings set org.gnome.desktop.interface cursor-theme 'capitaine-cursors'
gsettings set org.gnome.desktop.background picture-uri /usr/share/backgrounds/gnome/mojave-timed.xml
gsettings set org.gnome.desktop.screensaver picture-uri /usr/share/backgrounds/gnome/mojave-timed.xml
#
sudo sed -i '3s/custom/gnome/' ~/.config/automathemely/user_settings.json
sudo sed -i '7s/""/"Ant-Nebula"/' ~/.config/automathemely/user_settings.json
sudo sed -i '8s/""/"la-capitaine"/' ~/.config/automathemely/user_settings.json
sudo sed -i '9s/""/"Ant-Nebula"/' ~/.config/automathemely/user_settings.json
sudo sed -i '12s/""/"Dark-Side"/' ~/.config/automathemely/user_settings.json
sudo sed -i '13s/""/"la-capitaine"/' ~/.config/automathemely/user_settings.json
sudo sed -i '14s/""/"Ant-Nebula"/' ~/.config/automathemely/user_settings.json
sudo sed -i '65s/true/false/' ~/.config/automathemely/user_settings.json
#
#automathemely --setting desktop_environment=gnome
#automathemely --setting themes.gnome.light.gtk=Ant-Nebula
#automathemely --setting themes.gnome.light.icons=la-capitaine
#automathemely --setting themes.gnome.light.shell=Ant-Nebula
#automathemely --setting themes.gnome.dark.gtk=Dark-Side
#automathemely --setting themes.gnome.dark.icons=la-capitaine
#automathemely --setting themes.gnome.dark.shell=Ant-Nebula
#automathemely --setting location.auto_enabled=True
#automathemely --setting misc.notifications=False
automathemely --update
automathemely --restart
automathemely
#------------------------------------------------------------------------------------------------------------------------------------------
cat << EOT >> /home/$USER/.config/autostart/automathemelyrunner.desktop
[Desktop Entry]
Name=automathemelyrunner
Type=Application
Exec=python3 /usr/lib/python3.7/site-packages/automathemely/bin/autothscheduler.py
Hidden=false
NoDisplay=false
X-GNOME-Autostart-enabled=true
EOT
chmod +x /home/$USER/.config/autostart/automathemelyrunner.desktop
#------------------------------------------------------------------------------------------------------------------------------------------
sudo sed -i '144s/.xz//' /etc/makepkg.conf
# Grub Theme
wget -O - https://github.com/shvchk/poly-dark/raw/master/install.sh | bash
#
sudo grub-mkconfig -o /boot/grub/grub.cfg
echo
#
sudo rm /home/$USER/de
sudo rm /home/$USER/post
sudo rm /home/$USER/.config/autostart/postinstallscript.desktop
